name: Terraform Deployment for DEV and TEST

on:
  push:
    branches:
      - dev
      - test
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform  # Specify the subdirectory here
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Terraform Plan
      run: |
        if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          terraform plan -var-file="dev.tfvars"
        elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
          terraform plan -var-file="test.tfvars"
        fi
      working-directory: ./terraform  # Specify the subdirectory here
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    - name: Terraform Apply
      run: |
        if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          terraform apply -auto-approve -var-file="dev.tfvars"
        elif [ "${{ github.ref }}" == "refs/heads/test" ]; then
          terraform apply -auto-approve -var-file="test.tfvars"
        fi
      working-directory: ./terraform  # Specify the subdirectory here
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
