name: Terraform Deployment for PROD

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # Specify the environment for the job. Ensure that 'prod' is defined in your repository settings.
    environment: prod

    steps:
    - uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
      working-directory: .

    - name: Terraform Plan
      run: terraform plan -var-file="prod.tfvars"
      working-directory: .

    # The apply step will execute after manual approval if the environment has required reviewers.
    - name: Terraform Apply
      run: terraform apply -auto-approve -var-file="prod.tfvars"
      working-directory: .
